-- =============================================================================
-- practice-schema.sql — "TixHub" event-ticketing practice database
-- Target: PostgreSQL 16. Used by every file in 04-sql-databases/ and by
-- sql-practice.md. Safe to re-run: it drops and recreates everything.
--
-- Load it:
--   createdb tixhub
--   psql -d tixhub -f practice-schema.sql
--
-- Or with Docker:
--   docker run --name pg -e POSTGRES_PASSWORD=pg -p 5432:5432 -d postgres:16
--   docker cp practice-schema.sql pg:/tmp/ && \
--   docker exec -it pg psql -U postgres -c 'CREATE DATABASE tixhub'
--   docker exec -it pg psql -U postgres -d tixhub -f /tmp/practice-schema.sql
--
-- Tables (8):
--   employees    staff with a self-referencing manager_id (hierarchies, salaries)
--   customers    buyers, with self-referencing referred_by
--   venues       places events happen
--   events       things you can buy tickets for (N:1 venue)
--   orders       a customer's checkout (N:1 customer)
--   order_items  junction table orders <-> events (M:N) with quantity + price
--   payments     payment attempts per order (1:N), includes a deliberate double charge
--   page_views   200,000 generated rows so EXPLAIN plans are meaningful
--
-- Deliberate "flaws" you will find and fix in the exercises:
--   * customers 1 and 10 have the same e-mail ignoring case (unique is case-sensitive)
--   * order 7 was charged twice (duplicate SUCCEEDED payment)
--   * order 20 is PAID but has no successful payment
--   * order ids 12 and 17 are missing (gaps)
--   * NO index on page_views(event_id), page_views(customer_id), orders(customer_id),
--     order_items(event_id) — foreign keys do NOT get indexes automatically in Postgres.
-- =============================================================================

DROP TABLE IF EXISTS page_views, payments, order_items, orders, events, venues,
                     customers, employees CASCADE;

-- -----------------------------------------------------------------------------
-- employees: self-referencing FK (manager_id) -> recursive CTE practice
-- -----------------------------------------------------------------------------
CREATE TABLE employees (
    id          integer       PRIMARY KEY,
    full_name   text          NOT NULL,
    title       text          NOT NULL,
    department  text          NOT NULL CHECK (department IN ('Exec', 'Engineering', 'Sales', 'Support')),
    manager_id  integer       REFERENCES employees (id) ON DELETE SET NULL,
    salary      numeric(10,2) CHECK (salary > 0),          -- NULL = not yet set (NULL practice)
    hired_on    date          NOT NULL
);

INSERT INTO employees (id, full_name, title, department, manager_id, salary, hired_on) VALUES
 (1,  'Amara Osei',      'CEO',                 'Exec',        NULL, 250000, '2019-03-01'),
 (2,  'Bruno Silva',     'CTO',                 'Engineering', 1,    210000, '2019-06-15'),
 (3,  'Carmen Diaz',     'Staff Engineer',      'Engineering', 2,    180000, '2020-02-01'),
 (4,  'Dev Malhotra',    'Engineering Manager', 'Engineering', 2,    180000, '2020-09-10'),
 (5,  'Elena Petrova',   'Senior Engineer',     'Engineering', 4,    150000, '2021-04-19'),
 (6,  'Felix Wagner',    'Head of Sales',       'Sales',       1,    160000, '2020-01-06'),
 (7,  'Gita Rao',        'Account Executive',   'Sales',       6,     95000, '2022-07-01'),
 (8,  'Hugo Laurent',    'Account Executive',   'Sales',       6,     95000, '2023-01-09'),
 (9,  'Ines Costa',      'Engineer',            'Engineering', 5,    155000, '2023-05-22'),
 (10, 'Jamal Wright',    'Engineering Intern',  'Engineering', 5,      NULL, '2026-05-04'),
 (11, 'Keiko Sato',      'Support Specialist',  'Support',     6,     70000, '2024-11-11');

-- -----------------------------------------------------------------------------
-- customers
-- -----------------------------------------------------------------------------
CREATE TABLE customers (
    id           integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        text         NOT NULL UNIQUE,     -- case-sensitive! see exercises
    full_name    text         NOT NULL,
    city         text,                              -- nullable on purpose
    country      char(2)      NOT NULL,
    referred_by  integer      REFERENCES customers (id),
    created_at   timestamptz  NOT NULL DEFAULT now()
);

INSERT INTO customers (id, email, full_name, city, country, referred_by, created_at) VALUES
 (1,  'ava@example.com',    'Ava Patel',     'Toronto', 'CA', NULL, '2025-11-03 09:00+00'),
 (2,  'ben@example.com',    'Ben Okafor',    'Lagos',   'NG', 1,    '2025-11-20 12:30+00'),
 (3,  'chloe@example.com',  'Chloe Martin',  'Paris',   'FR', 1,    '2025-12-05 18:10+00'),
 (4,  'diego@example.com',  'Diego Ruiz',    'Madrid',  'ES', 2,    '2026-01-10 08:45+00'),
 (5,  'emma@example.com',   'Emma Schultz',  'Berlin',  'DE', NULL, '2026-01-15 20:00+00'),
 (6,  'farid@example.com',  'Farid Haddad',  'Toronto', 'CA', 5,    '2026-01-28 11:11+00'),
 (7,  'grace@example.com',  'Grace Kim',     'Seoul',   'KR', NULL, '2026-02-02 02:20+00'),
 (8,  'hiro@example.com',   'Hiro Tanaka',   'Tokyo',   'JP', 7,    '2026-02-14 05:00+00'),
 (9,  'isla@example.com',   'Isla Brown',    'London',  'GB', NULL, '2026-03-01 16:00+00'),
 (10, 'Ava@Example.com',    'Ava Patel',     'Toronto', 'CA', NULL, '2026-03-09 10:05+00'),
 (11, 'jonas@example.com',  'Jonas Berg',    NULL,      'NO', NULL, '2026-04-12 07:30+00'),
 (12, 'kofi@example.com',   'Kofi Mensah',   'Accra',   'GH', 2,    '2026-05-20 13:40+00');

-- -----------------------------------------------------------------------------
-- venues
-- -----------------------------------------------------------------------------
CREATE TABLE venues (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      text    NOT NULL,
    city      text    NOT NULL,
    capacity  integer NOT NULL CHECK (capacity > 0),
    UNIQUE (name, city)
);

INSERT INTO venues (id, name, city, capacity) VALUES
 (1, 'Maple Hall',       'Toronto', 2000),
 (2, 'Riverside Arena',  'London',  15000),
 (3, 'Blue Note Club',   'Berlin',  300),
 (4, 'Harbor Pavilion',  'Toronto', 5000);

-- -----------------------------------------------------------------------------
-- events (N:1 venues)
-- -----------------------------------------------------------------------------
CREATE TABLE events (
    id          integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id    integer       NOT NULL REFERENCES venues (id) ON DELETE RESTRICT,
    title       text          NOT NULL,
    category    text          NOT NULL CHECK (category IN ('CONCERT', 'COMEDY', 'SPORTS', 'CONFERENCE')),
    starts_at   timestamptz   NOT NULL,
    base_price  numeric(10,2) NOT NULL CHECK (base_price >= 0),
    status      text          NOT NULL DEFAULT 'SCHEDULED'
                              CHECK (status IN ('SCHEDULED', 'CANCELLED', 'COMPLETED'))
);

INSERT INTO events (id, venue_id, title, category, starts_at, base_price, status) VALUES
 (1,  1, 'Winter Jazz Night',   'CONCERT',    '2026-01-20 19:30+00',  45.00, 'COMPLETED'),
 (2,  2, 'Arena Rock Live',     'CONCERT',    '2026-02-15 20:00+00', 120.00, 'COMPLETED'),
 (3,  3, 'Late Laughs',         'COMEDY',     '2026-02-20 21:00+00',  25.00, 'COMPLETED'),
 (4,  4, 'DevConf 2026',        'CONFERENCE', '2026-03-10 09:00+00', 299.00, 'COMPLETED'),
 (5,  2, 'Cup Final Screening', 'SPORTS',     '2026-04-05 18:00+00',  35.00, 'COMPLETED'),
 (6,  1, 'Spring Strings',      'CONCERT',    '2026-04-18 19:00+00',  55.00, 'COMPLETED'),
 (7,  3, 'Open Mic',            'COMEDY',     '2026-05-02 20:00+00',  10.00, 'CANCELLED'),
 (8,  4, 'Summer Beats',        'CONCERT',    '2026-07-12 18:00+00',  80.00, 'SCHEDULED'),
 (9,  2, 'Data Summit',         'CONFERENCE', '2026-09-15 09:00+00', 349.00, 'SCHEDULED'),
 (10, 4, 'Stand-up Gala',       'COMEDY',     '2026-10-01 20:00+00',  60.00, 'SCHEDULED');

-- -----------------------------------------------------------------------------
-- orders (N:1 customers)
-- -----------------------------------------------------------------------------
CREATE TABLE orders (
    id           integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  integer      NOT NULL REFERENCES customers (id) ON DELETE RESTRICT,
    status       text         NOT NULL CHECK (status IN ('PENDING', 'PAID', 'CANCELLED', 'REFUNDED')),
    promo_code   text,
    created_at   timestamptz  NOT NULL DEFAULT now()
);

-- ids 12 and 17 intentionally missing
INSERT INTO orders (id, customer_id, status, promo_code, created_at) VALUES
 (1,  1,  'PAID',      NULL,       '2026-01-05 10:00+00'),
 (2,  1,  'PAID',      NULL,       '2026-01-06 11:15+00'),
 (3,  1,  'PAID',      NULL,       '2026-01-07 09:30+00'),
 (4,  2,  'PAID',      'NEWYEAR',  '2026-01-12 14:00+00'),
 (5,  3,  'CANCELLED', NULL,       '2026-01-15 16:45+00'),
 (6,  4,  'PAID',      NULL,       '2026-02-01 12:00+00'),
 (7,  1,  'PAID',      NULL,       '2026-02-10 18:20+00'),
 (8,  1,  'REFUNDED',  NULL,       '2026-02-11 19:05+00'),
 (9,  5,  'PAID',      NULL,       '2026-02-12 08:10+00'),
 (10, 2,  'PAID',      NULL,       '2026-02-18 21:30+00'),
 (11, 6,  'PENDING',   NULL,       '2026-02-25 13:00+00'),
 (13, 7,  'PAID',      'SPRING10', '2026-03-03 10:40+00'),
 (14, 3,  'PAID',      NULL,       '2026-03-05 15:00+00'),
 (15, 8,  'PAID',      NULL,       '2026-03-20 17:25+00'),
 (16, 1,  'PAID',      NULL,       '2026-04-01 12:00+00'),
 (18, 5,  'PAID',      NULL,       '2026-04-02 09:00+00'),
 (19, 4,  'PAID',      NULL,       '2026-05-15 11:11+00'),
 (20, 10, 'PAID',      NULL,       '2026-06-01 10:00+00');

-- -----------------------------------------------------------------------------
-- order_items: junction table for the M:N between orders and events.
-- Composite PK (order_id, event_id); unit_price is copied at purchase time
-- (a deliberate denormalization — prices change, receipts must not).
-- -----------------------------------------------------------------------------
CREATE TABLE order_items (
    order_id    integer       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    event_id    integer       NOT NULL REFERENCES events (id) ON DELETE RESTRICT,
    quantity    integer       NOT NULL CHECK (quantity > 0),
    unit_price  numeric(10,2) NOT NULL CHECK (unit_price >= 0),
    PRIMARY KEY (order_id, event_id)
);

INSERT INTO order_items (order_id, event_id, quantity, unit_price) VALUES
 (1,  1, 2,  45.00),
 (2,  3, 1,  25.00),
 (3,  2, 2, 120.00),
 (3,  3, 1,  25.00),
 (4,  2, 4, 108.00),
 (5,  1, 2,  45.00),
 (6,  4, 1, 299.00),
 (7,  4, 1, 299.00),
 (7,  5, 2,  35.00),
 (8,  6, 2,  55.00),
 (9,  4, 2, 299.00),
 (10, 5, 3,  35.00),
 (10, 6, 1,  55.00),
 (11, 8, 2,  80.00),
 (13, 6, 4,  49.50),
 (14, 5, 1,  35.00),
 (14, 7, 2,  10.00),
 (15, 8, 2,  80.00),
 (16, 9, 1, 349.00),
 (16, 8, 1,  80.00),
 (18, 9, 1, 349.00),
 (19, 8, 3,  80.00),
 (20, 9, 2, 349.00);

-- -----------------------------------------------------------------------------
-- payments (N:1 orders). Multiple attempts per order are normal (FAILED then
-- SUCCEEDED). Payment 8 is a duplicate charge of payment 7.
-- -----------------------------------------------------------------------------
CREATE TABLE payments (
    id          integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    integer       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    amount      numeric(10,2) NOT NULL CHECK (amount > 0),
    method      text          NOT NULL CHECK (method IN ('CARD', 'PAYPAL', 'GIFT_CARD')),
    status      text          NOT NULL CHECK (status IN ('SUCCEEDED', 'FAILED', 'REFUNDED')),
    created_at  timestamptz   NOT NULL DEFAULT now()
);

INSERT INTO payments (id, order_id, amount, method, status, created_at) VALUES
 (1,  1,   90.00, 'CARD',      'SUCCEEDED', '2026-01-05 10:01+00'),
 (2,  2,   25.00, 'CARD',      'SUCCEEDED', '2026-01-06 11:16+00'),
 (3,  3,  265.00, 'PAYPAL',    'SUCCEEDED', '2026-01-07 09:31+00'),
 (4,  4,  432.00, 'CARD',      'FAILED',    '2026-01-12 14:01+00'),
 (5,  4,  432.00, 'CARD',      'SUCCEEDED', '2026-01-12 14:03+00'),
 (6,  6,  299.00, 'CARD',      'SUCCEEDED', '2026-02-01 12:01+00'),
 (7,  7,  369.00, 'CARD',      'SUCCEEDED', '2026-02-10 18:21:00+00'),
 (8,  7,  369.00, 'CARD',      'SUCCEEDED', '2026-02-10 18:21:30+00'),
 (9,  8,  110.00, 'PAYPAL',    'SUCCEEDED', '2026-02-11 19:06+00'),
 (10, 8,  110.00, 'PAYPAL',    'REFUNDED',  '2026-02-14 10:00+00'),
 (11, 9,  598.00, 'GIFT_CARD', 'SUCCEEDED', '2026-02-12 08:11+00'),
 (12, 10, 160.00, 'CARD',      'SUCCEEDED', '2026-02-18 21:31+00'),
 (13, 13, 198.00, 'CARD',      'SUCCEEDED', '2026-03-03 10:41+00'),
 (14, 14,  55.00, 'PAYPAL',    'SUCCEEDED', '2026-03-05 15:01+00'),
 (15, 15, 160.00, 'CARD',      'SUCCEEDED', '2026-03-20 17:26+00'),
 (16, 16, 429.00, 'CARD',      'SUCCEEDED', '2026-04-01 12:01+00'),
 (17, 18, 349.00, 'CARD',      'SUCCEEDED', '2026-04-02 09:01+00'),
 (18, 19, 240.00, 'PAYPAL',    'SUCCEEDED', '2026-05-15 11:12+00');

-- -----------------------------------------------------------------------------
-- page_views: bulk, generated data (200,000 rows) for EXPLAIN / index practice.
-- setseed() makes random() deterministic, so everyone gets the same data.
-- ~70% of views are anonymous (customer_id IS NULL).
-- Event 9 ("Data Summit") is deliberately "hot" (~40% of all views).
-- -----------------------------------------------------------------------------
CREATE TABLE page_views (
    id           bigint       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_id     integer      NOT NULL REFERENCES events (id),
    customer_id  integer      REFERENCES customers (id),
    device       text         NOT NULL CHECK (device IN ('web', 'ios', 'android')),
    viewed_at    timestamptz  NOT NULL
);

SELECT setseed(0.42);

INSERT INTO page_views (event_id, customer_id, device, viewed_at)
SELECT
    CASE WHEN r1 < 0.40 THEN 9                       -- hot event
         ELSE 1 + floor(r2 * 10)::int END,           -- uniform 1..10
    CASE WHEN r3 < 0.70 THEN NULL
         ELSE 1 + floor(r4 * 12)::int END,           -- customers 1..12
    (ARRAY['web', 'ios', 'android'])[1 + floor(r5 * 3)::int],
    timestamptz '2026-01-01 00:00+00' + (r6 * interval '180 days')
FROM (
    SELECT random() AS r1, random() AS r2, random() AS r3,
           random() AS r4, random() AS r5, random() AS r6
    FROM generate_series(1, 200000)
) AS g;

-- -----------------------------------------------------------------------------
-- Identity columns: we inserted explicit ids, so move the sequences past them,
-- otherwise the next INSERT without an id fails with a duplicate-key error.
-- -----------------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('customers', 'id'), (SELECT max(id) FROM customers));
SELECT setval(pg_get_serial_sequence('venues',    'id'), (SELECT max(id) FROM venues));
SELECT setval(pg_get_serial_sequence('events',    'id'), (SELECT max(id) FROM events));
SELECT setval(pg_get_serial_sequence('orders',    'id'), (SELECT max(id) FROM orders));
SELECT setval(pg_get_serial_sequence('payments',  'id'), (SELECT max(id) FROM payments));

-- Fresh statistics so the planner's row estimates are sensible.
ANALYZE;

-- Quick sanity check (expected counts in comments):
SELECT 'employees'   AS tbl, count(*) FROM employees     -- 11
UNION ALL SELECT 'customers',   count(*) FROM customers  -- 12
UNION ALL SELECT 'venues',      count(*) FROM venues     -- 4
UNION ALL SELECT 'events',      count(*) FROM events     -- 10
UNION ALL SELECT 'orders',      count(*) FROM orders     -- 18
UNION ALL SELECT 'order_items', count(*) FROM order_items -- 23
UNION ALL SELECT 'payments',    count(*) FROM payments   -- 18
UNION ALL SELECT 'page_views',  count(*) FROM page_views; -- 200000
